/**
 * Threat Detection Engine Implementation
 *
 * Wires the world-model's causal engine to graceful-degradation's tier/alert
 * classification to produce structured ThreatAssessments from raw Observations.
 *
 * Design decisions:
 *   - World-model state (beliefs, entities, causal predictions) accumulates
 *     across calls so that each new observation builds on prior context.
 *   - Severity is translated to bio/synth health proxies fed into
 *     classifyDegradationTier(). Repeated high-severity observations compound,
 *     driving the tier from GREEN toward RED/BLACK.
 *   - Causal predictions are generated by the world-model's ICausalModel with
 *     an explicit "If [description]..." antecedent string.
 *   - A full consistency check runs after every belief update; contradictions
 *     are surfaced in the returned ThreatAssessment.
 *
 * All environment time is injected via Clock for deterministic testing.
 */

import { BeliefStore } from '../world-model/belief-store.js';
import { EntityModelStore } from '../world-model/entity-model-store.js';
import { CausalModel } from '../world-model/causal-model.js';
import { SituationAwareness } from '../world-model/situation-awareness.js';
import { WorldModel } from '../world-model/world-model.js';
import { classifyDegradationTier } from '../graceful-degradation/mvc.js';
import { AlertLevel, DegradationTier } from '../graceful-degradation/types.js';

import type { IWorldModel } from '../world-model/interfaces.js';
import type { BeliefId, EntityId } from '../world-model/types.js';
import type {
  Observation,
  ThreatAssessment,
} from './types.js';
import type { IThreatDetectionEngine } from './interfaces.js';

// ── Injectable clock ──────────────────────────────────────────────────────────

/** Abstracts time for deterministic testing. */
export interface Clock {
  now(): number;
}

// ── Helpers ───────────────────────────────────────────────────────────────────

let assessmentCounter = 0;

function nextAssessmentId(timestamp: number): string {
  return `assessment-${++assessmentCounter}-${timestamp}`;
}

/**
 * Map a DegradationTier to the corresponding AlertLevel.
 *
 * Mapping:
 *   GREEN  → None
 *   YELLOW → Warning
 *   ORANGE → Critical
 *   RED    → Emergency
 *   BLACK  → Emergency
 */
function tierToAlertLevel(tier: DegradationTier): AlertLevel {
  switch (tier) {
    case DegradationTier.Green:  return AlertLevel.None;
    case DegradationTier.Yellow: return AlertLevel.Warning;
    case DegradationTier.Orange: return AlertLevel.Critical;
    case DegradationTier.Red:    return AlertLevel.Emergency;
    case DegradationTier.Black:  return AlertLevel.Emergency;
  }
}

/**
 * Map a DegradationTier to a brief recommended response string.
 */
function tierToResponse(tier: DegradationTier, category: string): string {
  switch (tier) {
    case DegradationTier.Green:
      return `Monitor ${category} event — no immediate action required.`;
    case DegradationTier.Yellow:
      return `Escalate monitoring of ${category} event; prepare contingency protocols.`;
    case DegradationTier.Orange:
      return `Activate contingency protocols for ${category}; begin load-shifting.`;
    case DegradationTier.Red:
      return `Initiate emergency response for ${category}; consolidate to resilient substrates.`;
    case DegradationTier.Black:
      return `CRITICAL — ${category} has breached MVC threshold; execute emergency consolidation immediately.`;
  }
}

/**
 * Translate observation severity + confidence to a 0..1 threat level.
 *
 * Threat level = severity × confidence, clamped to [0, 1].
 */
function computeThreatLevel(severity: number, confidence: number): number {
  return Math.max(0, Math.min(1, severity * confidence));
}

/**
 * Map threat level to synthetic bio/synth health proxies for classifyDegradationTier().
 *
 * Both health scores start at 1.0 (fully healthy) and are reduced by the
 * accumulated worst-case threat level seen so far:
 *   bioHealth   = 1.0 − worstThreatLevel
 *   synthHealth = 1.0 − worstThreatLevel * 0.9   (synth slightly more resilient)
 *
 * The compounding ensures that repeated high-severity observations escalate
 * the tier; a single low-severity event does not trigger BLACK.
 */
function toHealthProxies(worstThreatLevel: number): { bioHealth: number; synthHealth: number } {
  return {
    bioHealth:   Math.max(0, 1.0 - worstThreatLevel),
    synthHealth: Math.max(0, 1.0 - worstThreatLevel * 0.9),
  };
}

// ── DefaultThreatDetectionEngine ──────────────────────────────────────────────

/**
 * Concrete implementation of IThreatDetectionEngine.
 *
 * Inject a custom IWorldModel and Clock for testing. If omitted, a fresh
 * in-memory WorldModel is created on construction (and reset() re-creates it).
 */
export class DefaultThreatDetectionEngine implements IThreatDetectionEngine {
  private worldModel: IWorldModel;
  private readonly clock: Clock;

  /** Running maximum of observed threat levels; drives tier escalation. */
  private worstThreatLevel = 0;

  constructor(deps?: { worldModel?: IWorldModel; clock?: Clock }) {
    this.clock = deps?.clock ?? { now: () => Date.now() };
    this.worldModel = deps?.worldModel ?? DefaultThreatDetectionEngine.createWorldModel();
  }

  // ── IThreatDetectionEngine ────────────────────────────────────────────────

  assess(observation: Observation, now?: number): ThreatAssessment {
    const timestamp = now ?? this.clock.now();
    const updatedBeliefs: BeliefId[] = [];

    // 1. Add a belief representing the observation to the world-model.
    const beliefId = this.worldModel.beliefs.addBelief(
      observation.description,
      observation.confidence,
      {
        type: observation.source === 'sensor' ? 'percept'
            : observation.source === 'report' ? 'testimony'
            : 'inference',
        referenceId: observation.id,
        description: `Observation ${observation.id}: ${observation.description}`,
      },
      [...observation.domainTags, observation.category],
    );
    updatedBeliefs.push(beliefId);

    // 2. If the same entity was observed before, revise its belief/trust model.
    if (observation.affectedEntityId != null) {
      this.worldModel.entities.upsertEntity(
        observation.affectedEntityId as EntityId,
        {
          timestamp,
          description: observation.description,
          deltaConfidence: -(observation.severity * observation.confidence),
        },
        {},
      );
    }

    // 3. Generate a causal prediction: "If [description], what are the consequences?"
    const antecedent = `${observation.description} (severity: ${observation.severity.toFixed(2)})`;
    const causalPrediction = this.worldModel.causal.predict(antecedent, observation.confidence);

    // 4. Compute threat level and update the worst-case accumulator.
    const threatLevel = computeThreatLevel(observation.severity, observation.confidence);
    if (threatLevel > this.worstThreatLevel) {
      this.worstThreatLevel = threatLevel;
    }

    // 5. Classify degradation tier using graceful-degradation's classifier.
    const { bioHealth, synthHealth } = toHealthProxies(this.worstThreatLevel);
    const degradationTier = classifyDegradationTier(bioHealth, synthHealth);
    const alertLevel = tierToAlertLevel(degradationTier);

    // 6. Run consistency check on the belief store.
    const consistencyReport = this.worldModel.runConsistencyCheck();

    // 7. Derive recommended response.
    const recommendedResponse = tierToResponse(degradationTier, observation.category);

    return {
      id: nextAssessmentId(timestamp),
      timestamp,
      triggeringObservation: observation,
      threatLevel,
      threatCategory: observation.category,
      degradationTier,
      alertLevel,
      causalPrediction,
      recommendedResponse,
      updatedBeliefs,
      consistencyReport,
    };
  }

  reset(): void {
    this.worstThreatLevel = 0;
    this.worldModel = DefaultThreatDetectionEngine.createWorldModel();
  }

  // ── Factory helper ────────────────────────────────────────────────────────

  private static createWorldModel(): IWorldModel {
    const beliefs = new BeliefStore();
    const entities = new EntityModelStore();
    const causal = new CausalModel();
    const situation = new SituationAwareness(beliefs, entities);
    return new WorldModel({ beliefs, entities, causal, situation });
  }
}
