/**
 * Threat Detection and Situational Awareness Engine — Core Type Definitions
 *
 * Defines the observation input format, threat assessment output format,
 * and scenario data structures used by the threat detection engine.
 *
 * The engine bridges three existing modules:
 *   - world-model: belief tracking and causal predictions
 *   - graceful-degradation: degradation tier and alert-level classification
 *   - sensorimotor: observation sources (sensor modalities)
 */

import { DegradationTier, AlertLevel } from '../graceful-degradation/types.js';
import type { BeliefId, CausalPrediction, ConsistencyReport } from '../world-model/types.js';

export { DegradationTier, AlertLevel };

// ── Observation input format ──────────────────────────────────────────────────

/**
 * Source of a raw observation fed into the threat detection engine.
 *
 * - sensor:      direct hardware / physical measurement
 * - inference:   derived from other observations or model output
 * - report:      human or agent-supplied text report
 * - simulation:  generated by a scenario runner for what-if analysis
 */
export type ObservationSource = 'sensor' | 'inference' | 'report' | 'simulation';

/**
 * High-level threat category associated with an observation.
 *
 * Used to route observations to appropriate response protocols and to tag
 * beliefs in the world model with matching domain labels.
 */
export type ThreatCategory =
  | 'physical-impact'
  | 'infrastructure-failure'
  | 'system-degradation'
  | 'biological-hazard'
  | 'adversarial-action'
  | 'environmental'
  | 'cascading-failure';

/**
 * A discrete observation fed into the threat detection engine.
 *
 * Observations are the raw input: sensor readings, incident reports,
 * simulation events. The engine translates each observation into a
 * ThreatAssessment via the world-model and graceful-degradation subsystems.
 *
 * Severity semantics:
 *   0.0 — no threat / nominal condition
 *   0.5 — moderate threat requiring monitoring
 *   1.0 — maximum severity / immediate action required
 */
export interface Observation {
  /** Unique identifier for this observation */
  readonly id: string;
  /** Wall-clock time the observation was recorded (ms since epoch) */
  readonly timestamp: number;
  readonly source: ObservationSource;
  readonly category: ThreatCategory;
  /** Human-readable description of what was observed */
  readonly description: string;
  /** Severity of the observed event: 0..1 */
  readonly severity: number;
  /** Confidence in the accuracy of this observation: 0..1 */
  readonly confidence: number;
  /** ID of the entity (system, region, agent) affected, if known */
  readonly affectedEntityId?: string;
  /** Domain tags used to tag/retrieve related beliefs in the world model */
  readonly domainTags: string[];
  /** Optional supplementary metadata (sensor readings, coordinates, etc.) */
  readonly metadata?: Record<string, unknown>;
}

// ── Threat assessment output format ──────────────────────────────────────────

/**
 * The assessed threat produced from a single observation.
 *
 * Aggregates results from three subsystems:
 *   - world-model: updated beliefs and causal prediction
 *   - graceful-degradation: current degradation tier and alert level
 *   - consistency check: logical coherence of the belief store after update
 *
 * Threat level semantics:
 *   0.0 — no credible threat
 *   0.5 — elevated threat warranting investigation
 *   1.0 — critical threat requiring immediate response
 */
export interface ThreatAssessment {
  /** Unique identifier for this assessment */
  readonly id: string;
  /** Time the assessment was produced (ms since epoch) */
  readonly timestamp: number;
  /** The observation that triggered this assessment */
  readonly triggeringObservation: Observation;
  /** Aggregate threat level 0..1 derived from severity, confidence, and causal model */
  readonly threatLevel: number;
  readonly threatCategory: ThreatCategory;
  /** Degradation tier produced by classifyDegradationTier(bioHealth, synthHealth) */
  readonly degradationTier: DegradationTier;
  /** Alert level derived from the degradation tier */
  readonly alertLevel: AlertLevel;
  /** Causal prediction generated by the world-model causal engine */
  readonly causalPrediction: CausalPrediction;
  /** Recommended immediate response action */
  readonly recommendedResponse: string;
  /** IDs of beliefs added or revised in the world-model belief store */
  readonly updatedBeliefs: BeliefId[];
  /** Consistency state of the world-model belief store after integrating this observation */
  readonly consistencyReport: ConsistencyReport;
}

// ── Scenario data structures ──────────────────────────────────────────────────

/**
 * A single timed event within a scenario timeline.
 *
 * `timeOffsetMs` is the number of milliseconds after the scenario base time
 * at which this observation occurs.
 */
export interface ScenarioEvent {
  readonly timeOffsetMs: number;
  readonly observation: Observation;
}

/**
 * A named sequence of observations that models a threat scenario over time.
 *
 * Feed a ThreatScenario into IScenarioRunner.run() to receive a ScenarioResult
 * with one ThreatAssessment per event.
 */
export interface ThreatScenario {
  readonly name: string;
  readonly description: string;
  /** Ordered timeline of events; need not be pre-sorted (runner sorts by offset). */
  readonly timeline: ScenarioEvent[];
}

/**
 * The full output of running a ThreatScenario through the scenario runner.
 *
 * Contains one assessment per scenario event, plus summary fields for the
 * final degradation state and overall timeline duration.
 */
export interface ScenarioResult {
  readonly scenario: ThreatScenario;
  /** One ThreatAssessment per ScenarioEvent, in chronological order. */
  readonly assessments: ThreatAssessment[];
  /** The degradation tier produced by the last assessment in the timeline. */
  readonly finalDegradationTier: DegradationTier;
  /** The alert level produced by the last assessment in the timeline. */
  readonly finalAlertLevel: AlertLevel;
  /** Total scenario duration in ms (last event offset − first event offset). */
  readonly durationMs: number;
}
