/**
 * SimulationManager — in-memory registry of active world simulations.
 *
 * Provides CRUD operations plus run/pause/step/stop lifecycle management
 * for multiple concurrent SimulationLoop instances.  Each simulation
 * emits state dumps to registered listeners after every tick.
 *
 * Design invariants:
 *  - State is entirely in-memory; the caller is responsible for persistence.
 *  - IDs are generated by the injected `idFactory` (defaults to UUID v4).
 *  - The clock is injected for testability.
 *  - Auto-run uses `setInterval`; injected `timerFactory` allows test mocks.
 */

import { SimulationLoop } from '../simulation/simulation-loop.js';
import { createVillageConfig } from '../simulation/scenarios/village.js';
import { createColonyConfig } from '../simulation/scenarios/colony.js';
import type { SimulationConfig, SimulationStateDump, SimulationEvent } from '../simulation/types.js';

// ── Types ────────────────────────────────────────────────────────────────────

export type SimulationStatus = 'idle' | 'running' | 'stopped';

export type ScenarioId = 'village' | 'colony';

export interface ScenarioDescriptor {
  readonly id: ScenarioId;
  readonly name: string;
  readonly description: string;
  readonly defaultAgentCount: number;
}

export interface SimulationRecord {
  readonly id: string;
  readonly name: string;
  readonly scenarioId: ScenarioId;
  status: SimulationStatus;
  readonly loop: SimulationLoop;
  /** Rolling window of the last MAX_HISTORY dumps. */
  readonly history: SimulationStateDump[];
  readonly createdAt: number;
  /** Tick at which this simulation was stopped (if applicable). */
  stoppedAtTick: number | null;
}

export interface CreateSimulationOptions {
  /** Human-readable label. */
  name: string;
  scenarioId: ScenarioId;
  /** Max ticks before the loop stops automatically. Default: 100. */
  maxTicks?: number;
}

/** Minimal summary for list views. */
export interface SimulationSummary {
  id: string;
  name: string;
  scenarioId: ScenarioId;
  status: SimulationStatus;
  currentTick: number;
  maxTicks: number | null;
  agentCount: number;
  createdAt: number;
}

// ── Constants ────────────────────────────────────────────────────────────────

const MAX_HISTORY = 200; // retain last N state dumps per simulation
const DEFAULT_MAX_TICKS = 100;
const AUTO_RUN_INTERVAL_MS = 250; // wall-clock delay between auto-run ticks

// ── Available scenarios ──────────────────────────────────────────────────────

export const AVAILABLE_SCENARIOS: ScenarioDescriptor[] = [
  {
    id: 'village',
    name: 'Village',
    description: 'Five villagers with distinct personalities exploring a small medieval village.',
    defaultAgentCount: 5,
  },
  {
    id: 'colony',
    name: 'Off-World Colony',
    description: 'Six colonists managing life aboard a remote outpost — command, engineering, and survival.',
    defaultAgentCount: 6,
  },
];

// ── Interfaces for injection ─────────────────────────────────────────────────

export interface ISimulationManagerDeps {
  /** Returns a unique string ID for each simulation. Default: crypto.randomUUID. */
  idFactory?: () => string;
  /** Returns current epoch-ms time. Default: Date.now. */
  clock?: () => number;
  /** Schedules a repeating callback. Default: setInterval. Returns a handle. */
  timerFactory?: (cb: () => void, ms: number) => NodeJS.Timeout;
  /** Clears a timer returned by timerFactory. Default: clearInterval. */
  timerCleaner?: (handle: NodeJS.Timeout) => void;
}

// ── SimulationManager ────────────────────────────────────────────────────────

export class SimulationManager {
  private readonly _sims = new Map<string, SimulationRecord>();
  private readonly _runHandles = new Map<string, NodeJS.Timeout>();
  private readonly _listeners = new Map<string, Array<(dump: SimulationStateDump) => void>>();

  private readonly _idFactory: () => string;
  private readonly _clock: () => number;
  private readonly _timerFactory: (cb: () => void, ms: number) => NodeJS.Timeout;
  private readonly _timerCleaner: (handle: NodeJS.Timeout) => void;

  constructor(deps: ISimulationManagerDeps = {}) {
    this._idFactory = deps.idFactory ?? (() => crypto.randomUUID());
    this._clock = deps.clock ?? (() => Date.now());
    this._timerFactory = deps.timerFactory ?? ((cb, ms) => setInterval(cb, ms));
    this._timerCleaner = deps.timerCleaner ?? ((h) => clearInterval(h));
  }

  // ── Scenarios ─────────────────────────────────────────────────────────────

  getScenarios(): ScenarioDescriptor[] {
    return AVAILABLE_SCENARIOS;
  }

  // ── CRUD ──────────────────────────────────────────────────────────────────

  create(opts: CreateSimulationOptions): SimulationRecord {
    const config = this._buildConfig(opts);
    const loop = new SimulationLoop(config, this._clock);
    const id = this._idFactory();

    const rec: SimulationRecord = {
      id,
      name: opts.name,
      scenarioId: opts.scenarioId,
      status: 'idle',
      loop,
      history: [],
      createdAt: this._clock(),
      stoppedAtTick: null,
    };

    loop.onTick((dump) => this._onTick(id, dump));

    this._sims.set(id, rec);
    return rec;
  }

  list(): SimulationSummary[] {
    return Array.from(this._sims.values()).map((r) => this._toSummary(r));
  }

  get(id: string): SimulationRecord | undefined {
    return this._sims.get(id);
  }

  delete(id: string): boolean {
    const rec = this._sims.get(id);
    if (!rec) return false;
    this._clearTimer(id);
    this._sims.delete(id);
    this._listeners.delete(id);
    return true;
  }

  // ── Lifecycle ─────────────────────────────────────────────────────────────

  /** Advance exactly one tick. Returns the resulting dump. */
  step(id: string): SimulationStateDump {
    const rec = this._require(id);
    if (rec.status === 'running') {
      throw new Error(`Simulation ${id} is already running — pause it first.`);
    }
    if (rec.status === 'stopped') {
      throw new Error(`Simulation ${id} has been stopped.`);
    }
    const dump = rec.loop.stepOnce();
    // onTick callback fires inside stepOnce, but we return the dump directly too
    return dump;
  }

  /**
   * Start auto-running at AUTO_RUN_INTERVAL_MS per tick.
   * If the loop reaches maxTicks, auto-run stops automatically.
   */
  startAutoRun(id: string): void {
    const rec = this._require(id);
    if (rec.status === 'running') return; // already running
    if (rec.status === 'stopped') {
      throw new Error(`Simulation ${id} has been stopped.`);
    }

    rec.status = 'running';
    const handle = this._timerFactory(() => {
      const r = this._sims.get(id);
      if (!r || r.status !== 'running') {
        this._clearTimer(id);
        return;
      }
      const dump = r.loop.stepOnce();
      // Check if maxTicks reached
      const maxTicks = r.loop.maxTicks;
      if (maxTicks !== null && r.loop.currentTick >= maxTicks) {
        r.status = 'stopped';
        r.stoppedAtTick = r.loop.currentTick;
        this._clearTimer(id);
        this._notify(id, dump);
      }
    }, AUTO_RUN_INTERVAL_MS);

    this._runHandles.set(id, handle);
  }

  /** Pause auto-run without resetting state. */
  pause(id: string): void {
    const rec = this._require(id);
    if (rec.status !== 'running') return;
    rec.status = 'idle';
    this._clearTimer(id);
  }

  /** Stop the simulation permanently. Cannot be resumed. */
  stop(id: string): void {
    const rec = this._require(id);
    if (rec.status === 'stopped') return;
    this._clearTimer(id);
    rec.loop.stop();
    rec.status = 'stopped';
    rec.stoppedAtTick = rec.loop.currentTick;
  }

  // ── Parameter injection ───────────────────────────────────────────────────

  /**
   * Inject an external event into the simulation.  The event will be included
   * in the next tick's percept list for all agents at/near the target location.
   */
  injectEvent(
    id: string,
    opts: {
      description: string;
      locationId: string;
      valenceHint?: number;
      noveltyHint?: number;
    },
  ): void {
    const rec = this._require(id);
    if (rec.status === 'stopped') {
      throw new Error(`Simulation ${id} has been stopped.`);
    }

    const now = this._clock();
    const tick = rec.loop.currentTick;

    // Build the visible-to list: all agents in the world
    const allAgentIds = rec.loop.world.getAgents().map((a) => a.agentId);

    const event: SimulationEvent = {
      id: `ext-${now}-${Math.random().toString(36).slice(2, 8)}`,
      tick,
      timestamp: now,
      actorId: 'world',
      locationId: opts.locationId,
      description: opts.description,
      visibleToAgentIds: allAgentIds,
      valenceHint: opts.valenceHint ?? 0,
      noveltyHint: opts.noveltyHint ?? 0.8,
    };

    rec.loop.queueExternalEvent(event);
  }

  /**
   * Update a personality trait for a specific NPC in the simulation.
   */
  setAgentTrait(id: string, agentId: string, traitId: string, value: number): void {
    const rec = this._require(id);
    if (rec.status === 'stopped') {
      throw new Error(`Simulation ${id} has been stopped.`);
    }

    const agent = rec.loop.world.getAgent(agentId);
    if (!agent) {
      throw new Error(`Agent "${agentId}" not found in simulation ${id}.`);
    }
    agent.setTrait(traitId, value);
  }

  // ── Listeners (for SSE) ───────────────────────────────────────────────────

  addListener(id: string, cb: (dump: SimulationStateDump) => void): void {
    if (!this._listeners.has(id)) {
      this._listeners.set(id, []);
    }
    this._listeners.get(id)!.push(cb);
  }

  removeListener(id: string, cb: (dump: SimulationStateDump) => void): void {
    const listeners = this._listeners.get(id);
    if (!listeners) return;
    const idx = listeners.indexOf(cb);
    if (idx !== -1) listeners.splice(idx, 1);
  }

  // ── Helpers ───────────────────────────────────────────────────────────────

  private _onTick(id: string, dump: SimulationStateDump): void {
    const rec = this._sims.get(id);
    if (!rec) return;
    rec.history.push(dump);
    if (rec.history.length > MAX_HISTORY) {
      rec.history.splice(0, rec.history.length - MAX_HISTORY);
    }
    this._notify(id, dump);
  }

  private _notify(id: string, dump: SimulationStateDump): void {
    const listeners = this._listeners.get(id);
    if (!listeners) return;
    for (const cb of listeners) {
      cb(dump);
    }
  }

  private _clearTimer(id: string): void {
    const handle = this._runHandles.get(id);
    if (handle !== undefined) {
      this._timerCleaner(handle);
      this._runHandles.delete(id);
    }
  }

  private _require(id: string): SimulationRecord {
    const rec = this._sims.get(id);
    if (!rec) throw new Error(`Simulation "${id}" not found.`);
    return rec;
  }

  private _toSummary(rec: SimulationRecord): SimulationSummary {
    return {
      id: rec.id,
      name: rec.name,
      scenarioId: rec.scenarioId,
      status: rec.status,
      currentTick: rec.loop.currentTick,
      maxTicks: rec.loop.maxTicks,
      agentCount: rec.loop.world.getAgents().length,
      createdAt: rec.createdAt,
    };
  }

  private _buildConfig(opts: CreateSimulationOptions): SimulationConfig {
    const maxTicks = opts.maxTicks ?? DEFAULT_MAX_TICKS;
    switch (opts.scenarioId) {
      case 'village':
        return createVillageConfig(maxTicks);
      case 'colony':
        return createColonyConfig(maxTicks);
      default:
        throw new Error(`Unknown scenario: ${String(opts.scenarioId)}`);
    }
  }
}
